-- Infrastructure NYC Yellow Taxi — Jour 1. Exécution : Run All dans Snowsight.
-- Rôles requis : USERADMIN et SYSADMIN.
-- Empreinte de la clé publique : SHA256:Tc8OhdoVAbUAkb3gIEfERWU219ya2UAMT+ACCgvswf4=
-- Les objets existants et leurs droits sont conservés.

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS TRANSFORMER
  COMMENT = 'Chargement et transformations du pipeline NYC Yellow Taxi';
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;

GRANT USAGE, OPERATE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.STAGING TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.MARTS TO ROLE TRANSFORMER;

USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS AIRFLOW_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = NYC_TAXI_WH
  DEFAULT_NAMESPACE = 'NYC_TAXI.RAW'
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApbTt9RXfEUOmmSc+GIBtDgSotr5+yOuoRzF2/wPaj2sg0l86EowTpTGX66/6jcm6VscytPcZNTFjNbco0N2zK4gf2tQqx8Wg9ehQAVEBEr1wFgdy+y27pfl6n1v0gltrvHc5an3Yk9D7ONr70iDntql4Elz7f8CcZ2OvyQj+ihxU6UWaS3DMwj1DK5T8EWTBgxO6OERHpDXV8mmfzF//QXJADzQAqTlbFmnrjnfbcqGkxGQ5JmNsLe3RntXJTc8NrVnW+2SkYeZ60Xi4oI88VLmqE4ahp2S9oCNpKaYf/ex38Gyh7Tv6Ub8Vy4r1Ep+68QfEjt0wc8VmdX2aP0OdIwIDAQAB'
  COMMENT = 'Service Airflow du pipeline NYC Yellow Taxi, authentification par clé';

-- Mise à jour des paramètres du service si le compte existe déjà.
ALTER USER AIRFLOW_SVC SET
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = NYC_TAXI_WH
  DEFAULT_NAMESPACE = 'NYC_TAXI.RAW'
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApbTt9RXfEUOmmSc+GIBtDgSotr5+yOuoRzF2/wPaj2sg0l86EowTpTGX66/6jcm6VscytPcZNTFjNbco0N2zK4gf2tQqx8Wg9ehQAVEBEr1wFgdy+y27pfl6n1v0gltrvHc5an3Yk9D7ONr70iDntql4Elz7f8CcZ2OvyQj+ihxU6UWaS3DMwj1DK5T8EWTBgxO6OERHpDXV8mmfzF//QXJADzQAqTlbFmnrjnfbcqGkxGQ5JmNsLe3RntXJTc8NrVnW+2SkYeZ60Xi4oI88VLmqE4ahp2S9oCNpKaYf/ex38Gyh7Tv6Ub8Vy4r1Ep+68QfEjt0wc8VmdX2aP0OdIwIDAQAB';
GRANT ROLE TRANSFORMER TO USER AIRFLOW_SVC;

-- Vérification des objets et des droits.
SHOW WAREHOUSES LIKE 'NYC_TAXI_WH';
SHOW SCHEMAS IN DATABASE NYC_TAXI;
SHOW GRANTS TO ROLE TRANSFORMER;
SHOW GRANTS OF ROLE TRANSFORMER;
SHOW GRANTS TO USER AIRFLOW_SVC;
DESC USER AIRFLOW_SVC;
